name: Build Android AAR

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK
        run: |
          sdkmanager "ndk;25.2.9519653"
          echo "ANDROID_NDK_HOME=${ANDROID_SDK_ROOT}/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Install gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          go install golang.org/x/mobile/cmd/gobind@latest
          gomobile init

      - name: Skip Geo Download
        run: |
          mkdir -p bin
          touch bin/geoip.dat
          touch bin/geosite.dat
          echo "package main; func main() {}" > download_geo/main.go

      - name: Build AAR
        run: python3 build/main.py android

      - name: Check output files
        run: ls -R

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: libXray-android
          path: libXray.aar
